export type GovernanceStatus =
  | 'STRONG'
  | 'IN PROGRESS'
  | 'EARLY STAGE'
  | 'PLANNED'
  | 'FOUNDATIONAL';

export interface GovernanceFunctionEntry {
  activities: string;  // Dynamic description of 1st Source's current activities
  status: GovernanceStatus;
}

// Full content for both PDF templates — generated by Claude per release
export interface PDFContent {
  // ── Intelligence Brief (Template 2) ──────────────────────────────────────
  whatHappened: string;           // 2-3 sentence narrative of the release
  whyItMattersPoints: string[];   // 4-6 bullet points specific to 1st Source
  nextSteps: string[];            // Exactly 3 concrete action steps
  riskComponents: {               // How the release touches each FS AI RMF pillar
    govern: string;
    map: string;
    measure: string;
    manage: string;
  };

  // ── Governance Readiness Summary (Template 1) ────────────────────────────
  contextStatement: string;       // 2-3 sentence intro for the readiness table
  governanceMapping: {            // Per-pillar current state at 1st Source
    govern: GovernanceFunctionEntry;
    map: GovernanceFunctionEntry;
    measure: GovernanceFunctionEntry;
    manage: GovernanceFunctionEntry;
  };
  keyMessagesForExaminers: string[]; // 4-6 examiner-facing bullet points
}

export interface ReleaseItem {
  title: string;
  url: string;
  publishedDate: string | null;
  description: string;
  sourceId: string;
  sourceName: string;
}

export interface AnalyzedRelease extends ReleaseItem {
  relevanceScore: number; // 1–10
  priority: 'high' | 'medium' | 'low' | 'not_relevant';
  summary: string;
  impactAnalysis: string;
  actionRequired: boolean;
  actionDetails: string;
  pdfContent?: PDFContent; // Present for high/medium priority items
}

export interface MonitorRunResult {
  newItemsFound: number;
  relevantItems: AnalyzedRelease[];
  emailSent: boolean;
  errors: string[];
}
